// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// vi_calc
Rcpp::NumericMatrix vi_calc(const Rcpp::NumericMatrix& zi, const Rcpp::NumericVector& sigma_vc, const Rcpp::NumericVector& rho_vc, const Rcpp::NumericVector& sigma_e);
RcppExport SEXP _ODSMethods_vi_calc(SEXP ziSEXP, SEXP sigma_vcSEXP, SEXP rho_vcSEXP, SEXP sigma_eSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type zi(ziSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type sigma_vc(sigma_vcSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type rho_vc(rho_vcSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type sigma_e(sigma_eSEXP);
    rcpp_result_gen = Rcpp::wrap(vi_calc(zi, sigma_vc, rho_vc, sigma_e));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ODSMethods_vi_calc", (DL_FUNC) &_ODSMethods_vi_calc, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_ODSMethods(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
