# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vi_calc <- function(zi, sigma_vc, rho_vc, sigma_e) {
    .Call(`_ODSMethods_vi_calc`, zi, sigma_vc, rho_vc, sigma_e)
}

